// app/about/page.tsx
import type { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: "About",
  description:
    "Developer Experience Engineer at ElevenLabs. Previously Developer Relations at Stripe.",
};

export default function AboutPage() {
  return (
    <div className="mx-auto max-w-5xl px-4 py-16 sm:px-8">
      <h1 className="font-heading mb-2 text-6xl tracking-widest text-white sm:text-8xl">
        ABOUT
      </h1>
      <div className="mb-16 h-0.5 w-16 bg-red" />

      {/* Bio section */}
      <div className="mb-16 flex flex-col gap-12 sm:flex-row sm:items-start">
        <div className="shrink-0">
          <div className="relative h-48 w-48 sm:h-64 sm:w-64">
            <Image
              src="/about-profile.jpg"
              alt="Paul Asjes"
              fill
              className="object-cover grayscale contrast-125"
              sizes="(max-width: 640px) 192px, 256px"
              priority
            />
            <div className="absolute inset-0 border border-border" />
            {/* Red corner accent */}
            <div className="absolute bottom-0 right-0 h-6 w-6 bg-red" />
          </div>
        </div>

        <div className="max-w-2xl space-y-6">
          <p className="font-body text-sm leading-loose text-off-white">
            Hello, I&apos;m Paul Asjes. I work as a Developer Experience
            Engineer at{" "}
            <a
              href="https://elevenlabs.io"
              target="_blank"
              rel="noopener noreferrer"
              className="text-red underline underline-offset-4 transition-colors hover:text-white"
            >
              ElevenLabs
            </a>
            . I focus on raising awareness, being the voice of the developer,
            and giving internal teams what they need to build great products.
          </p>
          <p className="font-body text-sm leading-loose text-off-white">
            Prior to ElevenLabs I ran Developer Relations at{" "}
            <a
              href="https://stripe.com"
              target="_blank"
              rel="noopener noreferrer"
              className="text-red underline underline-offset-4 transition-colors hover:text-white"
            >
              Stripe
            </a>
            . Before that I was a product engineer for 10+ years, working at
            Tumblr and various startups over the years. I started my career as a
            Flash developer back in the stone age of the internet, now preferring
            to work in the JavaScript ecosystem.
          </p>
        </div>
      </div>

      {/* Contact */}
      <section className="mb-16">
        <h2 className="font-heading mb-2 text-4xl tracking-widest text-white sm:text-5xl">
          CONTACT
        </h2>
        <div className="mb-8 h-0.5 w-10 bg-red" />
        <p className="font-body max-w-xl text-sm leading-loose text-off-white">
          The best way to reach me is via{" "}
          <a
            href="https://twitter.com/paul_asjes"
            target="_blank"
            rel="noopener noreferrer"
            className="text-red underline underline-offset-4 transition-colors hover:text-white"
          >
            Twitter / X
          </a>{" "}
          or{" "}
          <a
            href="mailto:hello@asjes.dev"
            className="text-red underline underline-offset-4 transition-colors hover:text-white"
          >
            email
          </a>
          . If inquiring about speaking at a conference, please include the
          dates, location, type of conference, and talk type in your message.
        </p>
      </section>

      {/* Uses */}
      <section>
        <h2 className="font-heading mb-2 text-4xl tracking-widest text-white sm:text-5xl">
          USES
        </h2>
        <div className="mb-8 h-0.5 w-10 bg-red" />
        <div className="grid gap-8 sm:grid-cols-2">
          <div>
            <h3 className="font-heading mb-4 text-2xl tracking-widest text-red">
              WEBSITE
            </h3>
            <ul className="font-body space-y-2 text-sm text-off-white">
              <li>
                <a
                  href="https://nextjs.org"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-red underline underline-offset-4 transition-colors hover:text-white"
                >
                  Next.js
                </a>
              </li>
              <li>
                <a
                  href="https://tailwindcss.com"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-red underline underline-offset-4 transition-colors hover:text-white"
                >
                  Tailwind CSS
                </a>
              </li>
              <li>
                <a
                  href="https://vercel.com"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-red underline underline-offset-4 transition-colors hover:text-white"
                >
                  Vercel
                </a>
              </li>
            </ul>
          </div>
          <div>
            <h3 className="font-heading mb-4 text-2xl tracking-widest text-red">
              SOFTWARE
            </h3>
            <ul className="font-body space-y-2 text-sm text-off-white">
              <li>
                Cursor (with{" "}
                <a
                  href="https://draculatheme.com/visual-studio-code"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-red underline underline-offset-4 transition-colors hover:text-white"
                >
                  Dracula
                </a>{" "}
                theme)
              </li>
              <li>
                <a
                  href="https://iterm2.com"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-red underline underline-offset-4 transition-colors hover:text-white"
                >
                  iTerm2
                </a>
              </li>
              <li>
                <a
                  href="https://bear.app"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-red underline underline-offset-4 transition-colors hover:text-white"
                >
                  Bear Notes
                </a>
              </li>
            </ul>
          </div>
        </div>
      </section>
    </div>
  );
}

// src/routes/about/+page.svelte
<script>
	import { MY_TWITTER_HANDLE } from '$lib/siteConfig';
</script>

<section class="flex justify-center">
	<div class="relative m-4 h-[150px] w-[150px] rounded-full sm:h-[250px] sm:w-[250px]">
		<img
			src="/about-profile.jpg"
			class="rounded-full bg-gradient-to-r from-white to-blue-400 p-1 filter"
			alt="Paul Asjes"
		/>
	</div>
</section>

<section
	class="mx-auto flex max-w-5xl flex-col items-start justify-center px-4 py-8 text-black dark:text-white sm:px-8"
>
	<h1 class="mb-4 text-3xl font-bold tracking-tight md:text-5xl">About me</h1>
	<div class="space-y-4">
		<p>
			Hello, I'm Paul Asjes. I work as a Developer Experience Engineer at ElevenLabs. I focus on raising
			awareness, being the voice of the developer and giving internal teams what they need to build
			great products.
		</p>
		<p>
			Prior to ElevenLabs I ran Developer Relations at Stripe. Before that I was a product engineer for
			10+ years, working at Tumblr and various start ups over the years. I started my career as a
			Flash developer back in the stone age of the internet, now preferring to work in the
			JavaScript ecosystem.
		</p>
	</div>
</section>

<section
	class="mx-auto flex max-w-5xl flex-col items-start justify-center px-4 py-8 text-black dark:text-white sm:px-8"
>
	<h1 class="mb-4 text-3xl font-bold tracking-tight md:text-5xl">Contact</h1>
	<p>
		If you want to get a hold of me, the best way is via <a
			href={`https://twitter.com/${MY_TWITTER_HANDLE}`}
			class="dark:text-blue-400">Twitter</a
		>
		or you can <a href="mailto:hello@asjes.dev" class="dark:text-blue-400">email</a> me directly. If
		inquiring about speaking at a conference, please include the dates, location, type of conference
		and talk type in your message.
	</p>
</section>

<section
	class="mx-auto flex w-full max-w-5xl flex-col items-start justify-center px-4 py-8 text-black dark:text-white sm:px-8"
>
	<h1 class="mb-4 text-3xl font-bold tracking-tight md:text-5xl">Uses</h1>

	<div class="m-4">
		<h2 class="mb-2 text-xl font-bold">Website</h2>
		<ul class="list-disc">
			<li><a href="https://svelte.dev/" class="dark:text-blue-400">Svelte</a></li>
			<li><a href="https://swyxkit.netlify.app/" class="dark:text-blue-400">Swyxkit</a></li>
			<li><a href="https://vercel.com/" class="dark:text-blue-400">Vercel</a></li>
		</ul>
	</div>

	<div class="m-4">
		<h2 class="mb-2 text-xl font-bold">Software</h2>
		<ul class="list-disc">
			<li>
				Cursor (with <a
					href="https://draculatheme.com/visual-studio-code"
					class="dark:text-blue-400">Dracula</a
				> theme)
			</li>
			<li><a href="https://iterm2.com/" class="dark:text-blue-400">iTerm2</a></li>
			<li><a href="https://bear.app/" class="dark:text-blue-400">Bear notes</a></li>
		</ul>
	</div>
</section>
